### ISSUE TITLE
Update Tutorial to use Hooks instead of class components

### ISSUE THREAD

**Issue by kentcdodds** [reactjs/react.dev#1782]
I think the react docs are a fantastic place for people to start getting into React. Seems like hooks are where we want people to learn React so it makes sense to update [the tutorial](https://reactjs.org/tutorial/tutorial.html) to use hooks instead.

Let me know what you think. I'm sure we'd get a lot of people willing to contribute this.

**Comment by selbekk** [comment]
I’d love to help out! 👋 we probably need to figure out how to rewrite stuff though - it might lead to a few new sections and a few deleted ones

**Comment by saranshkataria** [comment]
Would love to help too!

**Comment by abdusabri** [comment]
I'm definitely interested to help! 😄 

I've actually recreated the Tic Tac Toe tutorial using hooks.

**Solution 1**
In this solution, I've followed the original tutorial step-by-step, and tried to keep it as identical as possible.

[Here is the CodePen for the final result](https://codepen.io/abdusabri/pen/NZjPQV)

Following are the pens for all the code check points as provided in the tutorial:
- [Tic Tac Toe - Hooks - Starter](https://codepen.io/abdusabri/pen/RzoJgw)
- [Tic Tac Toe - Hooks - Point 1 (Passing Props)](https://codepen.io/abdusabri/pen/gNLKvr)
- [Tic Tac Toe - Hooks - Point 2 (Interactive Component)](https://codepen.io/abdusabri/pen/mZOKLV)
- [Tic Tac Toe - Hooks - Point 3A (Lifting State Up)](https://codepen.io/abdusabri/pen/qzqKge)
- [Tic Tac Toe - Hooks - Point 3B (Lifting State Up)](https://codepen.io/abdusabri/pen/rEWrOb)
- [Tic Tac Toe - Hooks - Point 4 (Taking Turns)](https://codepen.io/abdusabri/pen/QXGBpV)
- [Tic Tac Toe - Hooks - Point 5 (Declaring a Winner)](https://codepen.io/abdusabri/pen/jjyZNq)
- [Tic Tac Toe - Hooks - Point 6A (Adding Time Travel)](https://codepen.io/abdusabri/pen/EBWBbr)
- [Tic Tac Toe - Hooks - Point 6B (Adding Time Travel)](https://codepen.io/abdusabri/pen/gNWbJd)
- [Tic Tac Toe - Hooks - Point 6C (Adding Time Travel)](https://codepen.io/abdusabri/pen/NZjqgW)

**Solution 2**
[In this video](https://www.youtube.com/watch?v=G-aO5hzo1aw), featuring @gaearon and [Mattias Petter Johansson](https://github.com/mpj), Dan mentioned that the original tutorial had the logic of the application and history intertwined together, and that it would be interesting to create a custom hook and use reducers to separate them out. So, I've given it a shot - it was actually very interesting 😄 

I think this approach might be interesting to add as a bonus/advanced section to the tutorial to demonstrate what is possible using custom hooks.

[Here is a CodePen for the final result using a custom hook for history](https://codepen.io/abdusabri/pen/NZXJzo)

I think the main consideration would be to change the code to using declared functions instead of arrow functions.

I would be very interested to get feedback on the code, and will also gladly help with the documentation as well if you would like to proceed with this.

Thanks!

**Comment by nickmccurdy** [comment]
@abdusabri I'm not super familiar with the tutorial as I preferred to learn React via its docs, but as far as I can tell from the final step, this looks like a very solid translation of the original class logic to hooks. My only complains are ones I'd also have of the original.

**Comment by abdusabri** [comment]
Thanks for the feedback @nickmccurdy!

How should we proceed with this? Should i start working on the documentation? Do you know someone from the core team who should be mentioned here?

**Comment by nickmccurdy** [comment]
I started working on the docs (see #1788) but don't have a pull request yet, hopefully will soonish.

**Comment by abdusabri** [comment]
@nickmccurdy, thanks for working on the docs. The documentation I wanted to start working on is for the tutorial only. Basically, the write up and steps that would go along with the code I've provided. Docs for this issue and #1788 would be complimentary to each other, correct?

**Comment by nickmccurdy** [comment]
Yea, I think so. Personally I'm more familiar with the docs than tutorial, but this seems like a good approach for users that prefer the tutorial, as they are both alternative ways for new users to learn React.

**Comment by alansegar** [comment]
Linking this to https://github.com/reactjs/reactjs.org/pull/3063 from @DaniAkash which contains an updated tutorial using hooks
