### ISSUE TITLE
useCallback docs don't warn that the callback might run more than once

### ISSUE THREAD

**Issue by TimothyJones** [reactjs/react.dev#2334]
From the [useCallback docs](https://reactjs.org/docs/hooks-reference.html#usecallback): 

>`useCallback` will return a memoized version of the callback *that only changes if one of the dependencies has changed*.

(emphasis added). Then, the docs also say:

> `useCallback(fn, deps)` is equivalent to `useMemo(() => fn, deps)`.

but, in the [useMemo docs](https://reactjs.org/docs/hooks-reference.html#usememo)

> In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. 

Currently, the `useCallback` docs could mislead developers into writing code that will break in the future (eg, using `useCallback` for a function that must only run once).

It would be an improvement to have the same warning in the `useCallback` docs, even if only a small mention or warning to check the `useMemo` docs for the caveat.

**Comment by BartoszKlonowski** [comment]
Hello @TimothyJones, thanks for analysis and report!
Luckily, as I go through the latest version of [`useCallback`](https://react.dev/reference/react/useCallback) page in react.dev, I find it sufficient and lacking the concerns you pointed, so I believe this issue can be safely closed.
Let me know if you have any more remarks or see fields for further improvements.

**Comment by TimothyJones** [comment]
Oh wow! 5 years later 😂 Thank you, and I agree.

**Comment by denis-sokolov** [comment]
@BartoszKlonowski, I may be misreading something, but it seems that the same contradiction is still inthe docs the same way.

[useCallback page says](https://react.dev/reference/react/useCallback#should-you-add-usecallback-everywhere:~:text=React%20will%20give%20you%20the%20same%20function%20again%20if%20the%20dependencies%20have%20not%20changed%20since%20the%20last%20render) “React will give you the same function again if the dependencies have not changed since the last render”, and [useMemo page says](https://react.dev/reference/react/useMemo#memoizing-a-function:~:text=are%20completely%20equivalent) “[useCallback and useMemo] are completely equivalent”.

So is there a promise that useCallback will not purge the cache or is there not one?
