### ISSUE TITLE
When changing languages, user is sent to the home page instead of the current article

### ISSUE THREAD

**Issue by Seizeweb** [reactjs/react.dev#3760]
For some reason, I'm always sent by default to the FR version of the documentation (although my browser and laptops are both set in EN, Google still often sends me to French pages by default, I am French). 

But I don't like to read documentations in French, so I always switch to EN with the language selector, and then I'm sent back to the home page, instead of being redirected to the current page in the newly selected language.

It's pretty annoying as often had I came from Google and therefore wouldn't immediately know how to retrieve my way to the article through the doc's search or navigation sidebar.

## Reproduction steps
- Visit a page of the documentation in any language
- Switch languages
- You should now be on the home page

## Environment
- Firefox 89.0
- Macbook Pro M1

**Comment by amanjaingithub** [comment]
I have found the solution for this issue. We would have to store last visited pathname right before the language page is visited in local storage and add the pathname when the language is changed.

For example - 
A visted  https://reactjs.org/docs/getting-started.html#try-react . 
At this point the pathname would be "/docs/getting-started.html#try-react"
Now A has changed the language to Italian. This will add the pathname stored in the local storage to the main italian link which will become "https://it.reactjs.org/docs/getting-started.html#try-react". And A will be directed to same.

Since different languages have different repository for each. The code has to be added in all the repositories with no change required. Currently i am adding the changes to the languages other than In Progress and Need Contributors sections. Which makes the remaining  17 languages.

I found this way efficient than others. I am starting to make the pull request in each of the repositories. Please let me know if any change is required. I would be happy to take any suggestion.

**Comment by BartoszKlonowski** [comment]
Dears, I believe this issue is no longer valid, as react.dev is ENG by default without direct translation to be switched to (as translations are managed in separate repos).
Let me close this issue and related items.
Thank you!
