### ISSUE TITLE
It should not go back to `index page` after change the language.

### ISSUE THREAD

**Issue by creampnx-x** [reactjs/react.dev#4900]
What I think that It should go the page I just viewed, rather than go back to index page.

**Comment by BartoszKlonowski** [comment]
Hello @creampnx-x!
Considering the new approach to translations of the react.dev docs I don't think this issue is still valid.
Currently, there's no "dynamic" language change, but the separate page listing all separate websites for each language that is supported by the community.
Let me close this issue and the PR as outdated, please.
