### ISSUE TITLE
Tutorial Code Allows Overwrite of Squares

### ISSUE THREAD

**Issue by jamesobrooks** [reactjs/react.dev#4915]
# Tic-Tac-Toe Rule Violation

The code in the tutorial allows for overwriting played squares.

# Solution

Once the `handleClick` function has retrieved squares from state, immediately return if the particular square is already truthy.

**Comment by jamesobrooks** [comment]
I have a fix in [my fork](https://github.com/jamesobrooks/reactjs.org), but cannot create the PR to main. Is there a different branch I should branch from to start?

**Comment by rickhanlonii** [comment]
Thanks for catching this!

The new version of the tutorial covers this here: https://react.dev/learn/tutorial-tic-tac-toe#taking-turns

<img width="987" alt="Screenshot 2024-01-10 at 3 41 38 PM" src="https://github.com/reactjs/react.dev/assets/2440089/5eee34c8-ab44-4873-8a80-dc2c96b48e33">

Closing, since we're no longer updating the legacy docs.
