### ISSUE TITLE
tic-tac-toe local install has many npm audit issues

### ISSUE THREAD

**Issue by mingamellsIDBS** [reactjs/react.dev#5464]
On page https://beta.reactjs.org/learn/tutorial-tic-tac-toe#setup-for-the-tutorial - after copying and unzipping the ZIP, running npm install throws many npm autit issues.
Running npm audit fix --force, generates more!
Running npm audit fix --force for a second time seems to revert the state back to the original issues
From then on the process seems to just repeat so it is impossible to simply clear the issues.
Perhaps the zip, should be updated to a more recent and less vulnerable set of dependencies?

**Comment by rickhanlonii** [comment]
Yeah, nice find, it looks like we need to update the sandbox to react-scripts>=3.0.1, which may be a breaking change so it needs tested. Feel free to submit a PR.

**Comment by rickhanlonii** [comment]
If you want to work on this, please don't comment asking to assign this issue, just submit a PR.

**Comment by sbassong** [comment]
@rickhanlonii

I tried fixing this issue, though it might be a workaround since this is more of a problem from the dependencies themselves. Per the CRA team (in this thread https://github.com/facebook/create-react-app/issues/11647), it's not a real vulnerability.

Fix: Overriding the versions of the dependencies causing the warnings. 
`
"overrides": {
    "react-scripts": {
      "@svgr/webpack": "^6.2.1"
    },
    "postcss": "^8.4.33"
  }
`

The only problem is I can't submit a PR through the sandbox, especially since the tutorial repo isn't part of the react.dev repo. But here is the [forked sandbox with the fix added to package.json](https://codesandbox.io/p/devbox/react-dev-forked-fk2fzr?file=%2Fpackage.json%3A16%2C25&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrfo7emo00063b6h360qrs82%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrfo7emn00023b6hq8z0nlsz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrfo7emn00033b6hxvs01rvj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrfo7emn00053b6hwlo9sepw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrfo7emn00023b6hq8z0nlsz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrfo7emn00013b6he3nrivcq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrgmt9dx00023b6hy4p6sohb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A25%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A25%257D%255D%257D%255D%252C%2522id%2522%253A%2522clrfo7emn00023b6hq8z0nlsz%2522%252C%2522activeTabId%2522%253A%2522clrgmt9dx00023b6hy4p6sohb%2522%257D%252C%2522clrfo7emn00053b6hwlo9sepw%2522%253A%257B%2522id%2522%253A%2522clrfo7emn00053b6hwlo9sepw%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clrgxmfmz00bb3b6iuhuvt0y4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrgxmfmz00bb3b6iuhuvt0y4%2522%257D%252C%2522clrfo7emn00033b6hxvs01rvj%2522%253A%257B%2522id%2522%253A%2522clrfo7emn00033b6hxvs01rvj%2522%252C%2522activeTabId%2522%253A%2522clrgmtqw5005w3b6h0d9i0y6a%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrfobpsk004g3b6hxyzzxwgb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrfobpz2000iefhr3eksgswa%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clrgmtqw5005w3b6h0d9i0y6a%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

I am happy to get a proper PR going if someone can point me toward the best approach or when I figure it out eventually.

**Comment by rickhanlonii** [comment]
Ah, yeah if they're not real issues then I think we can close this, thanks for looking into it!

I'm not worried about the warnings because [`npm audit` is broken](https://overreacted.io/npm-audit-broken-by-design/)
