### ISSUE TITLE
"you-might-not-need-an-effect" page looks like needs to be edited.

### ISSUE THREAD

**Issue by roy-jung** [reactjs/react.dev#5911]
The example code and its description of `/learn/you-might-not-need-an-effect#fetching-data` don't seem to fit together. In the example code, there is no input tag and no state for it, but the description says `type "hello" fast. ...`, so the part of the description abount "racing conditions" that follows seems odd.

In the same vein, challenge 2 of 4 is also problematic. The requirement in question is `you need to make sure that getVisibleTodos() does not re-run when you type into the input.`, but `getVisibleTodos()` is not already being called when you type into the input in the first place.

**Comment by rickhanlonii** [comment]
> there is no input tag and no state for it,

The query is coming from a parent component, which is where the input would be.

> but getVisibleTodos() is not already being called when you type into the input in the first place.

Correct, as it says, to begin it only runs when you toggle the active TODOs. The challenge is to refactor the code  to remove the effect without allowing getVisibleTodos() to start firing every render (since, as you say, it doesn't currently and doesn't need to with the proper solution).
