### ISSUE TITLE
Fallback doesn't work as we expected

### ISSUE THREAD

**Issue by behnammodi** [reactjs/react.dev#6067]
While I was exploring the `useDeferredValue` feature on the React documentation website https://react.dev/reference/react/useDeferredValue, I came across an example that caught my attention. However, upon examining the provided code sandbox https://codesandbox.io/s/u1y9lp I noticed something peculiar. In the example, there is a fallback component specified within a `<Suspense>` component as follows:

```jsx
<Suspense fallback={<h2>Loading...</h2>}>
```

I expected the fallback happens when we don't have a list of result. if we shouldn't expect this behavior what is the point of using `Suspense` here? When it can have the same behavior without `Suspense`:

https://codesandbox.io/s/usedeferredvalue-without-suspense-eb3b6d

**Comment by rickhanlonii** [comment]
Yeah I can see how this is kind of confusing, but it's expected. The fallback is shown if you suspend on initial mount, but in this case when the search query is empty, we don't suspend. To verify, edit SearchResults.js to remove this block:

```
if (query === '') {
  return null;
}
```
Alternatively, you could provide a default search value (which may happen if you persist the search query to the URL in a real app:

```js
  const [query, setQuery] = useState('ab');
```

In either case, when you reload, you'll see that "Loading..." is displayed on initial mount. The reason "Loading..." isn't shown after initial mount is because the search term is wrapped in a deferred value, which avoids replacing existing content with a fallback.

You could probably go without the Suspense boundary in this case, but it's better to keep it since something else could suspend or the things above may change. Conceptually, the list is content that you can load separate from the search bar so it makes sense to wrap it in a boundary.
