### ISSUE TITLE
Missing doc: Rules of hooks

### ISSUE THREAD

**Issue by Ayc0** [reactjs/react.dev#6118]
In the previous website, we had the page "Rules of Hooks": https://legacy.reactjs.org/docs/hooks-rules.html, telling devs not to:
- call hooks in a if, other functions, loop
- that the order matters

But I cannot find any content like this in the new website:
- When I'm looking for `rule`
  <img width="765" alt="No match for 'rule'" src="https://github.com/reactjs/react.dev/assets/22725671/7ae15f57-f266-46b3-af6d-5e44f1b8fa8f">
- When I'm looking for `loop`
  <img width="750" alt="image" src="https://github.com/reactjs/react.dev/assets/22725671/4c3c249f-d0f8-489a-bb35-6bb9754fa964">

Is this a known issue and/or was done on purpose?

**Comment by tomtheisen** [comment]
It seems to be right here.

![image](https://github.com/reactjs/react.dev/assets/2049910/4a3530cd-cbff-4a92-a905-a9c7c971b670)

**Comment by Ayc0** [comment]
I know that this section exists, but it's within another page (the one introducing states), and not it's own so it's harder to discover it.

Also it doesn't have all the explanations the previous one had, nor mentions the ESLint plugin

**Comment by BartoszKlonowski** [comment]
Hello @Ayc0!
The page you are looking for can now be easily found here:
https://react.dev/reference/rules
also with the search:
<img width="2141" alt="obraz" src="https://github.com/user-attachments/assets/2fcc504b-7606-4a1f-93e1-ebc731e6e96c">

So as this issue seems to be no longer valid I will close this.
Thank you!
