### ISSUE TITLE
Not Found This page doesn’t exist

### ISSUE THREAD

**Issue by SoulYan** [reactjs/react.dev#6200]
This question is about the website https://react.docschina.org.
In the "Updating Arrays in State"submodule of the "LEARN REACT" ，at the end of "Making other changes to an array" section，
This link has expired（updating nested JavaScript objects）

**Comment by A7med3bdulBaset** [comment]
The correct link is [https://react.docschina.org/learn/updating-arrays-in-state#updating-objects-inside-arrays](https://react.docschina.org/learn/updating-arrays-in-state#updating-objects-inside-arrays) and should be fixed by [PR #1289](https://github.com/reactjs/zh-hans.react.dev/pull/1289) in the `zh-hans.react.dev` repo.
