### ISSUE TITLE
How to search new React documents in Dash.app

### ISSUE THREAD

**Issue by MuYunyun** [reactjs/react.dev#6222]
[Dash.app](https://kapeli.com/dash) is my favorite APP in daily development.It collects and integrates the use documents of various development languages ​​and frameworks.

But so far, the search for React on it is still the React tutorial documentation on the old reactjs.org website.

<img width="1280" alt="image" src="https://github.com/reactjs/react.dev/assets/19354791/05aafa49-98e6-4bbb-b371-43745a37e9a6">

Does anyone know how to search for the new react.dev docs on it?

**Comment by kahenya-anita** [comment]
Hello @MuYunyun, I noticed that when you search for React in Docsets, it displays all the versions including the latest version. However, the only available documentation pertains to React 16.8.

<img width="1440" alt="Screenshot 2023-08-14 at 9 40 58 AM" src="https://github.com/reactjs/react.dev/assets/62019551/ccfd6de9-b329-4b36-b7ca-9197649f1f70">

This can be solved by adding a new docset feed URL from the latest documentation

**Comment by MuYunyun** [comment]
@kahenya-anita How to check the currently available React documentation version is 16.8 and where can I add new docset feed URL？

**Comment by kahenya-anita** [comment]
@MuYunyun to add the feed URL you need to;

1. Install the doc2dash package because you are changing the URL into a docset feed
2. Add a .json file for Docset metadata
3. `doc2dash -A -n ReactDocset -d /path/to/docset/directory https://react.dev/` scraps data from the documentation into docset format. 
4. Host the generated feed URL to make it accessible 
5. Then go to downloads click add sign and add the Docset Feed URL

**Comment by rickhanlonii** [comment]
I think this is a question for [Dash.app](https://kapeli.com/dash), not for us.
