### ISSUE TITLE
Unable to add extension in EDGE browser. Error massage: The add-on could not be verified as the add-on manifest file is invalid.

### ISSUE THREAD

**Issue by XenonBird** [reactjs/react.dev#6242]
![Screenshot 2023-08-19 212729](https://github.com/reactjs/react.dev/assets/97312305/00949c6c-308c-404d-a04f-bb64c4181889)

**Comment by BartoszKlonowski** [comment]
Hey @XenonBird,
This repository you addressed with this issue is for the documentation of React, while the repository of the extension (add-on) you try to install is the [facebook/react](https://github.com/facebook/react/tree/main/packages/react-devtools-extensions) repository and this is where this issue should be reported.
Please report this to the proper repo if you still find it problematic to install, while I will close this issue here.
Thank you!
