### ISSUE TITLE
Why do we have separate websites for different languages can't we use some plugin like i18?

### ISSUE THREAD

**Issue by aryabyte21** [reactjs/react.dev#6434]

**Comment by pwbriggs** [comment]
Hi @aryabyte21!👋

Would you mind elaborating on your issue:

1. What's wrong with the current method of using subdomains ([es.react.dev](https://es.react.dev/), [ja.react.dev](https://ja.react.dev/), etc.) for different languages?
2. What's an alternative method you suggest? What benefits does it provide over the current method?

Thanks!😄

**Comment by rickhanlonii** [comment]
They're the same website, since they're all under the *.react.dev domain. Each language has it's own subdomain because using language subdomains to structure your multilingual site is the recommended best practice for optimizing SEO.

Once we have enough translations finished, we'll add a language dropdown like https://legacy.reactjs.org/ had to make it easier to change languages.
