### ISSUE TITLE
Sandpack examples with index.html files throw runtime errors

### ISSUE THREAD

**Issue by LookRain** [reactjs/react.dev#6487]
1. https://react.dev/learn/add-react-to-an-existing-project#step-2-render-react-components-anywhere-on-the-page
<img width="1024" alt="image" src="https://github.com/reactjs/react.dev/assets/11829847/269f009e-73ff-454b-baa1-4f874e0cc9a9">
2. https://react.dev/reference/react-dom/createPortal#rendering-react-components-into-non-react-server-markup
<img width="1054" alt="image" src="https://github.com/reactjs/react.dev/assets/11829847/aa362129-1d24-44bc-af7a-a33dc829bdac">

The issue seems to be because the `index.html` files defined in these examples are not used, instead, the `public/index.html` defined in the [template](https://github.com/reactjs/react.dev/blob/e98c3939a7c55e0ba2f0ae5beba3b7a1298b8d23/src/components/MDX/Sandpack/template.ts#L40) are used

**Comment by geeseyj** [comment]
Taking a look at this.

**Comment by geeseyj** [comment]
I opened a PR to revert the breaking change. 

The cause is the assumption here that all files within a sandpack example should be nested into a `src` directory. 
https://github.com/reactjs/react.dev/blob/e3c25d1a5f202bada2b0105b91e9a48935414c6c/src/components/MDX/Sandpack/createFileMap.ts#L7-L12

https://github.com/reactjs/react.dev/blob/e3c25d1a5f202bada2b0105b91e9a48935414c6c/src/components/MDX/Sandpack/createFileMap.ts#L30

This breaks examples that use `index.html` for instance because the merging of objects here results in the template file being used because the given `public/index.html` has been given the path `/src/public/index.html`

https://github.com/reactjs/react.dev/blob/e3c25d1a5f202bada2b0105b91e9a48935414c6c/src/components/MDX/Sandpack/SandpackRoot.tsx#L82

That gives us a couple options for a solution.
1. Make `createFileMap` know (arguably) too much by giving it a "whitelist" of file paths to not nest in a `/src/` directory.
2. Change all the Markdown files 😪 💤 .

At this point unfortunately I think option 2 is the un-sexy, more-correct option.
