### ISSUE TITLE
Extra spaces in code blocks running locally from Windows

### ISSUE THREAD

**Issue by poznianski** [reactjs/react.dev#6526]
I do a translation and noticed that on initial load everything looks good, but if I manually reload the page suddenly appears extra lines.
Initial: 
![image](https://github.com/reactjs/react.dev/assets/23197222/987901e0-9381-41c5-8f3d-212eaf8a4986)

After reload:
![image](https://github.com/reactjs/react.dev/assets/23197222/a0000521-ceeb-4ec5-82b5-65e2128341e9)

It goes okay again if i go to another page: 
![image](https://github.com/reactjs/react.dev/assets/23197222/17109395-a1b8-4072-86e4-e869ed02eb2a)

But if I reload the page:
![image](https://github.com/reactjs/react.dev/assets/23197222/8331a0c7-447c-4477-905a-e9ed0043b20c)

The code in my IDE does not change. That issue is only in runtime.

**Comment by pwbriggs** [comment]
Hey @poznianski!

I actually noticed this too yesterday. From what I can tell the issue comes from Git's `core.autocrlf` option. The documentation builder seems to be interpreting the Windows `\r\n` as two line breaks. That puts us Windows users in a bit of a tricky position.

The good thing is that most modern IDEs on Windows support using LF as well CRLF. I would recommend setting `core.autocrlf` to `input`, which preserves the LF at checkout and converts any stray CRLFs to LFs at commit.

If you want to change this behavior machine-wide, run `git config --global core.autocrlf input`. If you only want to change it for just the one repo, cd to the repo and run `git config core.autocrlf input`.

I've not tested, but you might need to empty your stash or re-checkout the branch after reconfiguring git. I'd also close the IDE before you run the command.

Hope this helps!

**Comment by poznianski** [comment]
> Hey @poznianski!
> 
> I actually noticed this too yesterday. From what I can tell the issue comes from Git's `core.autocrlf` option. The documentation builder seems to be interpreting the Windows `\r\n` as two line breaks. That puts us Windows users in a bit of a tricky position.
> 
> The good thing is that most modern IDEs on Windows support using LF as well CRLF. I would recommend setting `core.autocrlf` to `input`, which preserves the LF at checkout and converts any stray CRLFs to LFs at commit.
> 
> If you want to change this behavior machine-wide, run `git config --global core.autocrlf input`. If you only want to change it for just the one repo, cd to the repo and run `git config core.autocrlf input`.
> 
> I've not tested, but you might need to empty your stash or re-checkout the branch after reconfiguring git. I'd also close the IDE before you run the command.
> 
> Hope this helps!

Seems like you are right! But I have no opportunity to test it, coz I fixed  this annoying bug more radically. I switched to Manjaro as my main operating system. There is no bug 😁

Thanks for your investigation!

**Comment by pwbriggs** [comment]
Well, I guess that works too! 😃

@poznianski I don't actually have the permissions to close this issue myself (not a collaborator on the repo or the author of the issue), so would you mind doing that? Thanks!
