### ISSUE TITLE
Incorrect variables are listed as dependencies in useEffect()

### ISSUE THREAD

**Issue by Mhburg** [reactjs/react.dev#6528]
https://react.dev/learn/lifecycle-of-reactive-effects#all-variables-declared-in-the-component-body-are-reactive

![image](https://github.com/reactjs/react.dev/assets/14916037/1e07840f-b308-401c-9778-62f687c4de65)

In the code snippet shown above, it sets serverUrl as a dependency for the effect. However, the value of serverUrl would only change when the effect is run, which makes it "stable". In other words, even though the change of selectedServerUrl triggers a re-render, the effect would never run because react would come to the conclusion that serverUrl has the same values.

**Comment by pwbriggs** [comment]
Hi @Mhburg, thanks for opening this issue!

If I understand you correctly, you're saying that changing the `selectedServerUrl` prop would not trigger the effect. Is that correct?

When the `selectedServerUrl` prop changes, it changes the `serverUrl` variable, which in turn triggers the effect. `serverUrl` is defined outside the effect.

Hope this helps! Let me know if I've misunderstood what you're saying. Otherwise, if this resolves your issue, please remember to close it. Thanks!

**Comment by rickhanlonii** [comment]
Yeah great explination @pwbriggs. Let me know if that doesn't help @Mhburg!

**Comment by Mhburg** [comment]
Yes, it helps. It is my mistake. My eyes play trick on me leading me to think serverUrl was defined in the effect. Sorry about that.

**Comment by rickhanlonii** [comment]
No worries!
