### ISSUE TITLE
https://react.dev/learn/ is not showing right side menu in macbook pro m2 14.2.1

### ISSUE THREAD

**Issue by hasanahbd** [reactjs/react.dev#6563]
https://react.dev/learn/ this link is not showing right side menu bar , in Firefox and chrome in 100%[1] , but when I make the view 90%[2] it works fine. 

[1] https://github.com/reactjs/react.dev/assets/147480382/400a23f0-ac93-4c51-85a3-e31a81285816
[2] https://github.com/reactjs/react.dev/assets/147480382/e064cebe-461d-499b-a611-e125f32bcaea

**Comment by pwbriggs** [comment]
Hey there, @hasanahbd! 👋

I think the issue you're experiencing is due to `react.dev`'s [responsive web design](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design). If the browser narrower than a certain threshold, the site won't display the "On this page" section, because it would take up too much space. This makes the site work on a greater range of devices from desktop all the way to a smartphone. See the screencast below for an illustration of this.

https://github.com/reactjs/react.dev/assets/146312751/60db32f7-d02f-4b25-a612-70c711e73e1a

In your case, decreasing the zoom is essentially making the page "wider" (though the browser displays it in a smaller space).

It is debatable whether removing the table of contents is the best choice here. A potential alternative would be to instead collapse it into a menu, like the left sidebar does on very narrow displays (see the recording above).

Hope this helps!

**Comment by hasanahbd** [comment]
Thanks. 
Your screen cast is not playing

**Comment by rickhanlonii** [comment]
Yeah @pwbriggs is right, you can see yourself by resizing the browser window.

**Comment by pwbriggs** [comment]
@rickhanlonii maybe this is out of scope for this issue, but I think it is worth considering (as I said above) collapsing the table of contents somehow, rather than removing it. Not sure how difficult that would be to implement. It could be argued that a table of contents is possibly even *more* important on mobile devices (page height is greater, searching text in-page isn't as simple as just <kbd>ctrl</kbd>+<kbd>F</kbd>).

Of course, maybe something like this is already implemented and I'm missing it.

Thoughts?
