### ISSUE TITLE
[Bug]:  sidepanel is blocking main content

### ISSUE THREAD

**Issue by sify21** [reactjs/react.dev#6679]
### Summary

![image](https://github.com/reactjs/react.dev/assets/11829223/87e0c2c9-7485-412a-bbd1-108c54a38717)

### Page

https://react.dev/learn

### Details

firefox 123.0 on Ubuntu Server 23.10 with xfce4
![image](https://github.com/reactjs/react.dev/assets/11829223/5249eb40-8fd6-4727-800a-2909de4a1b39)

**Comment by pwbriggs** [comment]
Hey there, @sify21! 👋

I am unable to reproduce this bug in Firefox 123.0.1 on Ubuntu 23.10. A screenshot of my results is below.

Two action items for you to do that will help narrow down the issue:

1. Can you test again using [Firefox's troubleshoot mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode) to disable any extensions etc. that may be interfering with the page?
2. What happens if you test in other browsers? Other devices?

![image](https://github.com/reactjs/react.dev/assets/146312751/58882cf1-ce5a-42a4-8764-132d6e0efba8)

Thanks! ❤️

**Comment by sify21** [comment]
1. It's the same in trouble shoot mode
![image](https://github.com/reactjs/react.dev/assets/11829223/d7f96742-c176-4b0c-bd78-cd5ac472ce36)

2. Chrome displays fine
![image](https://github.com/reactjs/react.dev/assets/11829223/ff581d7c-32ec-4187-8a44-914c180df063)

**Comment by pwbriggs** [comment]
Huh, interesting. Can you try a different install of Firefox (re-install or use a different device)? I have no idea what would cause this.

**Comment by sify21** [comment]
It displays correctly now
