### ISSUE TITLE
[Bug]: Unable to access the React.dev website in some countries (e.g. Nigeria, Iran)

### ISSUE THREAD

**Issue by aghwotu** [reactjs/react.dev#6732]
### Summary

The react.dev website is not accessible within Nigeria.

The website opens with VPN
<img width="1440" alt="react-with-vpn" src="https://github.com/reactjs/react.dev/assets/22425217/6696c6a7-6e47-4248-8433-6858ec2de893">

The website doesn't open without VPN
<img width="1440" alt="react-without-vpn" src="https://github.com/reactjs/react.dev/assets/22425217/cccdc45e-695b-4424-ae61-c212694d2ddc">

### Page

https://react.dev/

**Comment by ojayde1** [comment]
I am experiencing a similar thing here.

**Comment by pwbriggs** [comment]
Already reported in https://github.com/reactjs/react.dev/issues/6661#issuecomment-2010899954. The site doesn't seem to be working in Iraq either.

Let's close this issue and track it over at #6661, because it's probably the same problem causing it.

**Comment by zaini** [comment]
I'm hosting a copy of the repo on Vercel if anyone would like to use that until this is resolved: https://react-dev-silk.vercel.app/

**Comment by Kimonic99** [comment]
lmao. wow.

**Comment by rickhanlonii** [comment]
Just an update on this: we are not intentionally blocking this. 

The issue seems to be some countries or ISPs have blocked the IP we are deployed at on Vercel. It doesn't impact legacy.reactjs.org, which is also deployed on Vercel, so I'm working with Vercel support to see how we can fix it. 

Seems related to this, because react.dev is also deployed at 76.76.21.21 but legacy.reactjs.dev is deployed at 76.76.21.164 https://github.com/orgs/vercel/discussions/4764

**Comment by rickhanlonii** [comment]
@aghwotu @ojayde1 (or anyone who can't access the site) would you be able to run the command from this debugging script for both react.dev and legacy.reactjs.org? If you don't want to upload it publicly, feel free to send the files to me at my username at gmail.

https://github.com/vercel-support/vercel-connect-debug

**Comment by rickhanlonii** [comment]
Update: this is now fixed, please test and confirm!

The issue was that our root domain was using `76.76.21.21`, which is blocked by some ISPs. We worked with support to understand the settings we needed to use other IPs, and we're now using `76.76.21.22` and ` 76.76.21.142` which shouldn't be blocked. 

Let me know if you still see this issue or if it comes up again and we can re-open.

**Comment by player412** [comment]
Not Working here in India.

**Comment by kmg454** [comment]
Have also this problem from Holland, can't reach 76.76.21.21 from ISP KPN and my Fiberglas connection. Using a VPN solve the problem for me. Just note that some other users with a KPN connection did not have this problem.

**Comment by Myagnik** [comment]
> Not Working here in India.

for me as well

**Comment by om1976** [comment]
All your IPs (76.76.21.21, 76.76.21.22, 76.76.21.142) are blocked in Ukraine. You can check at https://uablocklist.com/blocklist?query=76.76.21.21
